config/routes.rb
Rails.application.routes.draw do
  resources :migrations
  #post 'kyujins/new',to: "kyujins#create"
  get 'kyujins/confirmation'
  resources :kyujins

  root "checks#show"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kyujin.rb
class Kyujin < ApplicationRecord
end

app/models/migration.rb
class Migration < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery
end

app/controllers/kyujins_controller.rb
class KyujinsController < ApplicationController
  before_action :set_kyujin, only: %i[ show edit update destroy ]

  # GET /kyujins or /kyujins.json
  def index
    @kyujins = Kyujin.all
  end

  # GET /kyujins/1 or /kyujins/1.json
  def show
    if request.post? then
      if params["check"] then
        @value = "本社"
      elsif
        @value = "支店"
      else 
        @value = "工場"
      end
    end
  end


  def confirmation
  end
  # GET /kyujins/new
  def new
    @kyujin = Kyujin.new
  end

  # GET /kyujins/1/edit
  def edit
  end

  def self.hankaku?(str)
    return nil if str.nil?
    # 半角のみOKなので、全角が混ざっているとfalseが返る
    unless str.to_s =~ /^[ -~｡-ﾟ]*$/
      return false
    end
  return true
  end


  # POST /kyujins or /kyujins.json
  def create
    @kyujin = Kyujin.new(kyujin_params)

      p @kyujin
      p "----------------------------"
    respond_to do |format|
      if @kyujin.save
        format.html { redirect_to kyujin_url(@kyujin), notice: "Kyujin was successfully created." }
        format.json { render :show, status: :created, location: @kyujin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @kyujin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kyujins/1 or /kyujins/1.json
  def update
    respond_to do |format|
      if @kyujin.update(kyujin_params)
        format.html { redirect_to kyujin_url(@kyujin), notice: "Kyujin was successfully updated." }
        format.json { render :show, status: :ok, location: @kyujin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @kyujin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kyujins/1 or /kyujins/1.json
  def destroy
    @kyujin.destroy

    respond_to do |format|
      format.html { redirect_to kyujins_url, notice: "Kyujin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kyujin
      @kyujin = Kyujin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def kyujin_params
      params.require(:kyujin).permit(:kaisya, :furigana, :yubin, :jusyo, :banchi, :jigyou, :tantou, :denwa, :fax, :mail, :home, :bosyu, :syokusyu, :saiyoujo, :kinmuti, :kinmuzikan, :kyuyo, :syoyo, :nenkankyu, :oubo, :biko,:honsyaz,:shitenz,:coujous,:jakan,:others)
    end
  end

app/controllers/migrations_controller.rb
class MigrationsController < ApplicationController
  before_action :set_migration, only: %i[ show edit update destroy ]

  # GET /migrations or /migrations.json
  def index
    @migrations = Migration.all
  end

  # GET /migrations/1 or /migrations/1.json
  def show
  end

  # GET /migrations/new
  def new
    @migration = Migration.new
  end

  # GET /migrations/1/edit
  def edit
  end

  # POST /migrations or /migrations.json
  def create
    @migration = Migration.new(migration_params)

    respond_to do |format|
      if @migration.save
        format.html { redirect_to migration_url(@migration), notice: "Migration was successfully created." }
        format.json { render :show, status: :created, location: @migration }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @migration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /migrations/1 or /migrations/1.json
  def update
    respond_to do |format|
      if @migration.update(migration_params)
        format.html { redirect_to migration_url(@migration), notice: "Migration was successfully updated." }
        format.json { render :show, status: :ok, location: @migration }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @migration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /migrations/1 or /migrations/1.json
  def destroy
    @migration.destroy

    respond_to do |format|
      format.html { redirect_to migrations_url, notice: "Migration was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_migration
      @migration = Migration.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def migration_params
      params.require(:migration).permit(:AddDateToKyujins, :honsyas, :shitens, :cojous, :kinmusonotas)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kyujins_helper.rb
module KyujinsHelper
end

app/helpers/migrations_helper.rb
module MigrationsHelper
end

app/views/kyujins/_form.html.erb
<div class = "html1">
  <%= form_with(model: @kyujin, local: true ,html: {name: "form"}) do |form| %>

  <div class="midashi">
    <p>本校への求人ついて。<br>
      当学校の在校生、または卒業生への求人がございましたら下記フォームより求人募集としてお寄せください。<br><br>
      <span>※</span>印の項目は入力必須となっています。漏れのないように入力してください。<br>
      数字を記入する際には半角で入力してください
    </p>
  </div>

  <%= image_tag '素材1.png', class: 'img1'%>

    <div class="f_table">
      <table border="1" cellspacing="0">

      <tr class="field">
        <th>求人者<span class="gami">※</span></th>
        <td>ふりがな<%= form.text_field :furigana %><br>
        会社名・団体名<%= form.text_field :kaisya %><br>
        担当者名<%= form.text_field :tantou %><br>
        電話番号（例:0853-72-2500）<%= form.text_field :denwa %><br>
        メールアドレス(任意)<%= form.text_field :mail %><br>
        </td>
      </tr>


      <tr class="field">
        <th><%= form.label :jigyou,"事業内容" %></th>
        <td><%= form.text_field :jigyou %></td>
      </tr>

        <tr class="field">
        <th>所在地<span class="gami">※</span></th>
        <td>郵便番号<br><%= form.text_field :yubin %><br>
        住所（例:島根県出雲市斐川町富村1000-8）<%= form.text_field :jusyo %></td>
      </tr>


      <tr class="field">
        <th>職種<span class="gami">※</span></th>
      <td><%= form.select :syokusyu, ['IT・Web', '医療', '介護福祉','教育・保育・研究','販売・接客・サービス','運輸・物流','製造・整備','土地・建物','美容・ファッション','出版・広告・マスコミ','金融・保険','オフィス系','警察・消防・セキュリティ','その他'], {include_blank: '選択してください'}, 
      class: 'field' %></td></tr>
      </tr>

      <tr>
        <th><%= form.label :bosyu,"求人数" %></th>
        <td><%= form.text_field :bosyu , size: 10 %>人
        <%= form.check_box :jakan %>
        <%= form.label :jakan,"若干名" %><br>※採用人員が若干名の場合は、「若干名」にチェックを入れてください。
        </td>
      </tr>

      <tr class="field">
        <th><%= form.label :shigoto,"仕事内容" %></th>
        <td><%= form.text_field :shigoto %></td>
      </tr>

      <tr class="field">
        <th>勤務先<span class="gami">※</span></th>
        <td>
  <ul>
    <li>
          <%= form.check_box :honsyaz %>
          <%= form.label :honsyaz,"本社" %>
    </li>
    <li>
          <%= form.check_box(:shitenz) %>
          <%= label_tag(:shitenz,"支店") %>
    </li>
    <li>
          <%= form.check_box(:coujous) %>
          <%= label_tag(:coujous,"工場") %>
    </li>


  </ul>
        その他<br><%= form.text_field :others %></td>
      </tr>

      <tr>
        <th><%= form.label :zyugyoin,"従業員数" %></th>
        <td><%= form.text_field :zyugyoin , size: 10 %>人</td>
      </tr>

      <tr>
        <th><%= form.label :kinmuzikan,"勤務時間" %></th>
        <td> 平日<br>
        <%= form.text_field :kinmuzikan, size: 3 %>時
        <%= form.text_field :kinmuzikan, size: 3 %>分   ~    
        <%= form.text_field :kinmuzikan, size: 3 %>時
        <%= form.text_field :kinmuzikan, size: 3 %>分まで<br>
        土・日・祝<br>
        <%= form.text_field :kinmuzikan, size: 3 %>時
        <%= form.text_field :kinmuzikan, size: 3 %>分   ~    
        <%= form.text_field :kinmuzikan, size: 3 %>時
        <%= form.text_field :kinmuzikan, size: 3 %>分まで</td>
      </tr>

      <tr>
        <th><%= form.label :kyuyo,"給与" %></th>
        <td><%= form.text_field :kyuyo , size: 10 %>円</td>
      </tr>

      <tr>
        <th><%= form.label :teate,"手当" %></th>
        <td><%= form.text_field :teate , size: 10 %>円</td>
      </tr>

      <tr class="field">
        <th><%= form.label :oubo,"応募書類" %></th>
        <td><%= check_box_tag :oubo %>
        <%= label_tag :oubo, "履歴書" %>
        <%= check_box_tag :oubo %>
        <%= label_tag :oubo, "卒業見込証明書"%>
        <%= check_box_tag :oubo %>
        <%= label_tag :oubo, "成績証明書" %><br>
        <%= check_box_tag :oubo %>
        <%= label_tag :oubo, "健康診断書" %>
        <%= check_box_tag :oubo %>
        <%= label_tag :oubo, "推薦書" %></td>
      </tr>

      <tr>
        <th><%= form.label :kikan,"応募締め切り" %></th>
        <td><%= check_box_tag :kikan %>
        <%= label_tag :kikan, "なし" %>
        <%= check_box_tag :kikan %>
        <%= label_tag :kikan, "随時" %><br>
        <%= check_box_tag :kikan %>
        <%= label_tag :kikan, "指定日" %><br>
        <%= form.text_field :kikan, size: 3 %>月
        <%= form.text_field :kikan, size: 3 %>日   ~    
        <%= form.text_field :kikan, size: 3 %>月
        <%= form.text_field :kikan, size: 3 %>日
        </td>
      </tr>

      <tr class="field">
        <th><%= form.label :senko,"選考方法" %></th>
        <td><%= form.text_field :senko %></td>
      </tr>

      <tr class="field">
        <th><%= form.label :senko,"履歴書" %></th>
        <td><%= form.text_field :senko %></td>
      </tr>     

      <div class="kaigyo">
        <tr class="field">
          <th><%= form.label :biko,"備考" %></th>
          <td><%= form.text_area :biko, :size=>"40x5" %></td>
        </tr>
      </div>
    </table>
  </div>

  <%= form.submit "完了"%>
<%# <a href="javascript:form.submit()" class="f_submit">送信</a> %>

<% end %>
</div>

app/views/kyujins/confirmation.erb
<h1>送信しました</h1>
<%= image_tag '素材3.png', class: 'img3'%>

<div class="s_back">
<%= link_to "戻る", kyujins_path %> 
</div>

app/views/kyujins/edit.html.erb
<%= render 'form', kyujin: @kyujin %>

<%= link_to 'Show', @kyujin %> |
<%= link_to 'Back', kyujins_path %>

app/views/kyujins/index.html.erb
<h1>求人情報一覧</h1>
<div class="table">
  <table>
    <table border="1" cellspacing="0">
      <tr class="title">
        <td width="200">会社名</td>
        <td width="100">業種</td>
        <td width="120">所在地</td>
        <td width="150">勤務地</td>
        <td width="100">職種</td>
        <td width="30">採用人数</td>
        <td width="40">給与</td>
        <td width="350">詳細</td>
      </tr>
    </div>
  <tbody>
    <% @kyujins.each do |kyujin| %>
      <tr>
        <td><%= link_to kyujin.kaisya, kyujin %></td>
        <td><%= kyujin.jigyou %></td>
        <td><%= link_to kyujin.jusyo, kyujin %></td>
        <td><%= kyujin.kinmuti %></td>
        <td><%= kyujin.syokusyu %></td>
        <td><%= kyujin.bosyu %></td>
        <td><%= kyujin.kyuyo %></td>
        <td><%= kyujin.biko %></td>

    <% end %>
  </tbody>
</table>
</div>

<br><br><br><br><br><br><br><br>
<div class="n_submit">
<%= link_to '求人募集フォーム', new_kyujin_path %>
</div>

app/views/kyujins/new.html.erb
<h1>企業様専用 求人申込フォーム</h1>
<%= render 'form', kyujin: @kyujin %>



<div class="back">
    <%= link_to '戻る', kyujins_path %>
</div>

app/views/kyujins/show.html.erb
<div class = "html2">
<h2><strong>※この内容でよろしいですか</strong></h2>

  <%= image_tag '素材2.png', class: 'img2'%>

<div class="s_table">
  <table border="1" cellspacing="0">
    <tr class="s_tr">
      <th><strong>ふりがな</strong></th>
      <td><%= @kyujin.furigana %></td>
    </tr>

    <tr class="s_tr">
      <th><strong>会社名・団体名</strong></th>
      <td><%= @kyujin.kaisya %></td>
    </tr>

    <tr class="s_tr">
      <th><strong>担当者名</strong></th>
      <td><%= @kyujin.tantou %></td>
    </tr>

    <tr class="s_tr">
      <th><strong>電話番号</strong></th>
      <td><%= @kyujin.denwa %></td>
    </tr>

    <tr class="s_tr">
      <th><strong>メールアドレス</strong></th>
      <td><%= @kyujin.mail %></td>
    </tr>

    <tr class="s_tr">
      <th><strong>事業内容</strong></th>
      <td><%= @kyujin.jigyou %></td>
    </tr>

    <tr class="s_tr">
      <th><strong>郵便番号</strong></th>
      <td><%= @kyujin.yubin %></td>
    </tr>

    <tr class="s_tr">
      <th><strong>住所</strong></th>
      <td><%= @kyujin.jusyo %></td>
    </tr>

    <tr class="s_tr">
      <th><strong>職種</strong></th>
      <td><%= @kyujin.syokusyu %></td>
    </tr>

    <tr class="s_tr">
      <th><strong>求人数</strong></th>
      <td><%= @kyujin.bosyu %>
      <%= "若干名" if @kyujin.jakan %></td>
    </tr>

    <tr class="s_tr">
      <th><strong>仕事内容</strong></th>
      <td><%= @kyujin.shigoto %></td>
    </tr>

    <tr class="s_tr">
      <th><strong>勤務先</strong></th>
      <td>
        <%= "本社" if @kyujin.honsyaz %>
        <%= "支店" if @kyujin.shitenz %>
        <%= "工場" if @kyujin.coujous %>
        <%= @kyujin.others %>
      </td>

    <tr class="s_tr">
      <th><strong>従業員数</strong></th>
      <td><%= @kyujin.zyugyoin %></td>
    </tr>

    <tr class="s_tr">
      <th><strong>勤務時間</strong></th>
      <td><%= @kyujin.kinmuzikan %></td>
    </tr>

    <tr class="s_tr">
      <th><strong>給与</strong></th>
      <td><%= @kyujin.kyuyo %></td>
    </tr>

    <tr class="s_tr">
      <th><strong>手当</strong></th>
      <td><%= @kyujin.teate %></td>
    </tr>

    <tr class="s_tr">
      <th><strong>応募書類</strong></th>
      <td><%= @kyujin.oubo %></td>
    </tr>

    <tr class="s_tr">
      <th><strong>応募締め切り</strong></th>
      <td><%= @kyujin.kikan %></td>
    </tr>

    <tr class="s_tr">
      <th><strong>選考方法</strong></th>
      <td><%= @kyujin.senko %></td>
    </tr>

    <tr class="s_tr">
      <th><strong>履歴書</strong></th>
      <td><%= @kyujin.rirekisyo %></td>
    </tr>

    <tr class="s_tr">
      <th><strong>備考</strong></th>
      <td><%= safe_join(@kyujin.biko.split("\n"),tag(:br)) %></td>
     </tr>
  </table>
</div>

<div class="s_back">
<%= link_to "戻る", :back %> 
</div>

<div class="s_submit">
<%= link_to '送信', kyujins_confirmation_path %>
</div>

<div class="pageFooter">
  <img src="http://www.icc.core.ac.jp/1549001753/">
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sotsuken</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>